### ISSUE TITLE
How to initialize with custom location?

### ISSUE THREAD

**Issue by eriweb** [wkoszek/lastpass-ansible#1]
I tried initializing with an existing `.lastpass-ansible.conf` in the hopes that it would store the vault password there, but I get an error saying `lastpass-ansible: File .lastpass-ansible.conf exists!`.

Is it possible to initialize the vault password in a custom location, or do I have to move it to the desired location after initializing?

**Comment by wkoszek** [comment]
Let me clarify stuff a bit. Vault password is getting stored in LastPass, never in any config file. The name of the LastPass "site" is stored in `.lastpass-ansible.conf`. This file is per-project, as I assume different projects have different Ansible Vaults. Example:

~/Project/web_service
~/Project/yourpage.com

If you `lastpass-ansible --init` in these two directories, you'll end up with:

~/Project/web_service/.ansible-lastpass.conf
~/Project/yourpage.com/.ansible-lastpass.conf

Now the way `~/Project/web_service/.ansible-lastpass.conf` works is that it tells Ansible where the password to your vault is stored. This file has just "LastPass directory" name in it. So you can put "Secret Notes/SSH" if you want, but by default it is "Ansible_Vault/web_service"

With this clarified, let me know if it already answered your question, or whether things are still dark.

**Comment by wkoszek** [comment]
@terbolous Did it help?

**Comment by wkoszek** [comment]
@terbolous Ping. Unless you confirm/deny that docs are reflecting what I explained above, I'll close this issue.

**Comment by wkoszek** [comment]
Heard nothing from the original report. Closing.
